<?xml version="1.0"?>
<!DOCTYPE LIGO_LW [
<!ELEMENT LIGO_LW ((LIGO_LW|Comment|Param|Time|Table|Array|Stream)*)>
<!ATTLIST LIGO_LW Name CDATA #IMPLIED Type CDATA #IMPLIED>
<!ELEMENT Comment (#PCDATA)>
<!ELEMENT Param (#PCDATA)>
<!ATTLIST Param Name CDATA #IMPLIED Type CDATA #IMPLIED Dim CDATA #IMPLIED
                Unit CDATA #IMPLIED>
<!ELEMENT Table (Comment?,Column*,Stream?)>
<!ATTLIST Table Name CDATA #IMPLIED Type CDATA #IMPLIED>
<!ELEMENT Column EMPTY>
<!ATTLIST Column Name CDATA #IMPLIED Type CDATA #IMPLIED Unit CDATA #IMPLIED>
<!ELEMENT Array (Dim*,Stream?)>
<!ATTLIST Array Name CDATA #IMPLIED Type CDATA #IMPLIED>
<!ELEMENT Dim (#PCDATA)>
<!ATTLIST Dim Name CDATA #IMPLIED>
<!ELEMENT Stream (#PCDATA)>
<!ATTLIST Stream Name CDATA #IMPLIED Type (Remote|Local) "Local"
          Delimiter CDATA "," Encoding CDATA #IMPLIED Content CDATA #IMPLIED>
<!ELEMENT Time (#PCDATA)>
<!ATTLIST Time Name CDATA #IMPLIED Type (GPS|Unix|ISO-8601) "ISO-8601">
]>
<LIGO_LW Name="Diagnostics Test">
  <LIGO_LW Name="Header" Type="Global">
    <Param Name="Flag" Type="string">TestParameters</Param>
    <Param Name="Creator" Type="string">Diagnostics system</Param>
    <Param Name="TestType" Type="string">FFT</Param>
    <Param Name="TestName" Type="string">1998-2001, by Daniel Sigg</Param>
    <Param Name="Supervisory" Type="string">Standard</Param>
    <Param Name="TestIterator" Type="string">Repeat</Param>
    <Time Name="TestTime" Type="GPS">916817849.0</Time>
    <Time Name="TestTimeUTC" Type="ISO-8601">2009-01-24 07:37:15</Time>
    <Param Name="InputSource" Type="string">online</Param>
    <Param Name="Comment" Type="string"></Param>
  </LIGO_LW>
  <LIGO_LW Name="Def" Type="Defaults">
    <Param Name="Flag" Type="string">TestParameters</Param>
    <Param Name="AllowCancel" Type="boolean">true</Param>
    <Param Name="NoStimulus" Type="boolean">false</Param>
    <Param Name="NoAnalysis" Type="boolean">false</Param>
    <Param Name="KeepTraces" Type="int">100</Param>
    <Param Name="SiteDefault" Type="byte">.</Param>
    <Param Name="SiteForce" Type="byte"> </Param>
    <Param Name="IfoDefault" Type="byte"> </Param>
    <Param Name="IfoForce" Type="byte"> </Param>
    <Param Name="Reconnect" Type="boolean">false</Param>
    <Param Name="PlotWindowLayout[1]" Type="int">2</Param>
    <Param Name="PlotWindows" Type="int">1</Param>
    <Param Name="CalibrationRecords" Type="int">0</Param>
  </LIGO_LW>
  <LIGO_LW Name="Find" Type="Optimization">
    <Param Name="Flag" Type="string">TestParameters</Param>
    <Param Name="Enable" Type="boolean">true</Param>
    <Param Name="Change" Type="boolean">true</Param>
    <Param Name="Type" Type="int">0</Param>
    <Param Name="Value" Type="double">0</Param>
    <Param Name="Function" Type="int">0</Param>
    <Param Name="Param" Type="double" Dim="2">0	100</Param>
    <Param Name="Method" Type="int">0</Param>
  </LIGO_LW>
  <LIGO_LW Name="Lidax" Type="Fantom">
    <Param Name="Flag" Type="string">TestParameters</Param>
  </LIGO_LW>
  <LIGO_LW Name="Sync" Type="Synchronization">
    <Param Name="Flag" Type="string">TestParameters</Param>
    <Param Name="Type" Type="int">0</Param>
    <Time Name="Start" Type="GPS">916792852.0</Time>
    <Param Name="Wait" Type="double" Unit="s">-0</Param>
    <Param Name="Repeat" Type="int">1</Param>
    <Param Name="RepeatRate" Type="double" Unit="s">0</Param>
    <Param Name="SlowDown" Type="double" Unit="s">0</Param>
  </LIGO_LW>
  <LIGO_LW Name="Test" Type="TestParameter">
    <Param Name="Flag" Type="string">TestParameters</Param>
    <Param Name="Subtype" Type="string">FFT</Param>
    <Param Name="StartFrequency" Type="double" Unit="Hz">0</Param>
    <Param Name="StopFrequency" Type="double" Unit="Hz">7400</Param>
    <Param Name="BW" Type="double" Unit="Hz">0.3</Param>
    <Param Name="Overlap" Type="double">0.5</Param>
    <Param Name="Window" Type="int">1</Param>
    <Param Name="RemoveDC" Type="boolean">true</Param>
    <Param Name="AChannels" Type="int">1</Param>
    <Param Name="AverageType" Type="int">0</Param>
    <Param Name="Averages" Type="int">10</Param>
    <Param Name="SettlingTime" Type="double">0.1</Param>
    <Param Name="StimulusType[0]" Type="int">0</Param>
    <Param Name="StimulusType[1]" Type="int">0</Param>
    <Param Name="StimulusType[2]" Type="int">0</Param>
    <Param Name="StimulusType[3]" Type="int">0</Param>
    <Param Name="StimulusType[4]" Type="int">0</Param>
    <Param Name="StimulusFrequency[0]" Type="double" Unit="Hz">100</Param>
    <Param Name="StimulusFrequency[1]" Type="double" Unit="Hz">100</Param>
    <Param Name="StimulusFrequency[2]" Type="double" Unit="Hz">100</Param>
    <Param Name="StimulusFrequency[3]" Type="double" Unit="Hz">100</Param>
    <Param Name="StimulusFrequency[4]" Type="double" Unit="Hz">100</Param>
    <Param Name="StimulusAmplitude[0]" Type="double">0</Param>
    <Param Name="StimulusAmplitude[1]" Type="double">0</Param>
    <Param Name="StimulusAmplitude[2]" Type="double">0</Param>
    <Param Name="StimulusAmplitude[3]" Type="double">0</Param>
    <Param Name="StimulusAmplitude[4]" Type="double">0</Param>
    <Param Name="StimulusOffset[0]" Type="double">0</Param>
    <Param Name="StimulusOffset[1]" Type="double">0</Param>
    <Param Name="StimulusOffset[2]" Type="double">0</Param>
    <Param Name="StimulusOffset[3]" Type="double">0</Param>
    <Param Name="StimulusOffset[4]" Type="double">0</Param>
    <Param Name="StimulusPhase[0]" Type="double">0</Param>
    <Param Name="StimulusPhase[1]" Type="double">0</Param>
    <Param Name="StimulusPhase[2]" Type="double">0</Param>
    <Param Name="StimulusPhase[3]" Type="double">0</Param>
    <Param Name="StimulusPhase[4]" Type="double">0</Param>
    <Param Name="StimulusRatio[0]" Type="double">0.5</Param>
    <Param Name="StimulusRatio[1]" Type="double">0.5</Param>
    <Param Name="StimulusRatio[2]" Type="double">0.5</Param>
    <Param Name="StimulusRatio[3]" Type="double">0.5</Param>
    <Param Name="StimulusRatio[4]" Type="double">0.5</Param>
    <Param Name="StimulusFrequencyRange[0]" Type="double" Unit="Hz">10000</Param>
    <Param Name="StimulusFrequencyRange[1]" Type="double" Unit="Hz">10000</Param>
    <Param Name="StimulusFrequencyRange[2]" Type="double" Unit="Hz">10000</Param>
    <Param Name="StimulusFrequencyRange[3]" Type="double" Unit="Hz">10000</Param>
    <Param Name="StimulusFrequencyRange[4]" Type="double" Unit="Hz">10000</Param>
    <Param Name="StimulusAmplitudeRange[0]" Type="double">0</Param>
    <Param Name="StimulusAmplitudeRange[1]" Type="double">0</Param>
    <Param Name="StimulusAmplitudeRange[2]" Type="double">0</Param>
    <Param Name="StimulusAmplitudeRange[3]" Type="double">0</Param>
    <Param Name="StimulusAmplitudeRange[4]" Type="double">0</Param>
    <Param Name="MeasurementChannel[0]" Type="string" Unit="channel">L1:LSC-DARM_ERR</Param>
    <Param Name="MeasurementActive[0]" Type="boolean">true</Param>
    <Param Name="MeasurementChannel[1]" Type="string" Unit="channel">L1:LSC-MICH_CTRL</Param>
    <Param Name="MeasurementActive[1]" Type="boolean">true</Param>
    <Param Name="MeasurementChannel[2]" Type="string" Unit="channel">L1:LSC-PRC_CTRL</Param>
    <Param Name="MeasurementActive[2]" Type="boolean">true</Param>
  </LIGO_LW>
  <LIGO_LW Name="Plot[1][0]" Type="Plot">
    <Param Name="Flag" Type="string">Settings</Param>
    <Param Name="Name" Type="string">Default</Param>
    <Param Name="TracesGraphType" Type="string">Power spectrum</Param>
    <Param Name="TracesActive[0]" Type="boolean">true</Param>
    <Param Name="TracesAChannel[0]" Type="string" Unit="channel">L1:LSC-DARM_ERR</Param>
    <Param Name="TracesBChannel[0]" Type="string" Unit="channel"></Param>
    <Param Name="TracesActive[1]" Type="boolean">true</Param>
    <Param Name="TracesAChannel[1]" Type="string" Unit="channel">L1:LSC-DARM_ERR(REF1)</Param>
    <Param Name="TracesBChannel[1]" Type="string" Unit="channel"></Param>
    <Param Name="TracesActive[2]" Type="boolean">false</Param>
    <Param Name="TracesAChannel[2]" Type="string" Unit="channel">L1:LSC-PRC_CTRL</Param>
    <Param Name="TracesBChannel[2]" Type="string" Unit="channel"></Param>
    <Param Name="TracesActive[3]" Type="boolean">false</Param>
    <Param Name="TracesAChannel[3]" Type="string" Unit="channel"></Param>
    <Param Name="TracesBChannel[3]" Type="string" Unit="channel"></Param>
    <Param Name="TracesActive[4]" Type="boolean">false</Param>
    <Param Name="TracesAChannel[4]" Type="string" Unit="channel"></Param>
    <Param Name="TracesBChannel[4]" Type="string" Unit="channel"></Param>
    <Param Name="TracesActive[5]" Type="boolean">false</Param>
    <Param Name="TracesAChannel[5]" Type="string" Unit="channel"></Param>
    <Param Name="TracesBChannel[5]" Type="string" Unit="channel"></Param>
    <Param Name="TracesActive[6]" Type="boolean">false</Param>
    <Param Name="TracesAChannel[6]" Type="string" Unit="channel"></Param>
    <Param Name="TracesBChannel[6]" Type="string" Unit="channel"></Param>
    <Param Name="TracesActive[7]" Type="boolean">false</Param>
    <Param Name="TracesAChannel[7]" Type="string" Unit="channel"></Param>
    <Param Name="TracesBChannel[7]" Type="string" Unit="channel"></Param>
    <Param Name="TracesPlotStyle" Type="int" Dim="8">0	0	0	0	0	0	0	0</Param>
    <Param Name="TracesLineAttrColor" Type="int" Dim="8">2	4	3	28	6	7	5	1</Param>
    <Param Name="TracesLineAttrStyle" Type="int" Dim="8">1	1	1	1	1	1	1	1</Param>
    <Param Name="TracesLineAttrWidth" Type="double" Dim="8">1	1	1	1	1	1	1	1</Param>
    <Param Name="TracesMarkerAttrColor" Type="int" Dim="8">2	4	3	28	6	7	5	1</Param>
    <Param Name="TracesMarkerAttrStyle" Type="int" Dim="8">20	22	21	23	29	27	2	5</Param>
    <Param Name="TracesMarkerAttrSize" Type="double" Dim="8">1	1	1	1	1	1	1	1</Param>
    <Param Name="TracesBarAttrColor" Type="int" Dim="8">2	4	3	28	6	7	5	1</Param>
    <Param Name="TracesBarAttrStyle" Type="int" Dim="8">1001	1001	1001	1001	1001	1001	1001	1001</Param>
    <Param Name="TracesBarAttrWidth" Type="double" Dim="8">0.1	0.1	0.1	0.1	0.1	0.1	0.1	0.1</Param>
    <Param Name="RangeAxisScale" Type="int" Dim="2">0	1</Param>
    <Param Name="RangeRange" Type="int" Dim="2">1	1</Param>
    <Param Name="RangeRangeFrom" Type="double" Dim="2">20	1e-07</Param>
    <Param Name="RangeRangeTo" Type="double" Dim="2">200	0.001</Param>
    <Param Name="RangeBin" Type="int">1</Param>
    <Param Name="RangeBinLogSpacing" Type="boolean">false</Param>
    <Param Name="UnitsXValues" Type="int">0</Param>
    <Param Name="UnitsYValues" Type="int">0</Param>
    <Param Name="UnitsXUnit" Type="string">default</Param>
    <Param Name="UnitsYUnit" Type="string">default</Param>
    <Param Name="UnitsXMag" Type="int">0</Param>
    <Param Name="UnitsYMag" Type="int">0</Param>
    <Param Name="UnitsXSlope" Type="double">1</Param>
    <Param Name="UnitsYSlope" Type="double">1</Param>
    <Param Name="UnitsXOffset" Type="double">0</Param>
    <Param Name="UnitsYOffset" Type="double">0</Param>
    <Param Name="CursorActive" Type="boolean" Dim="2">false	false</Param>
    <Param Name="CursorTrace" Type="int">0</Param>
    <Param Name="CursorStyle" Type="int">1</Param>
    <Param Name="CursorType" Type="int">0</Param>
    <Param Name="CursorX" Type="double" Dim="2">11	200</Param>
    <Param Name="CursorH" Type="double" Dim="2">0	100</Param>
    <Param Name="CursorValid" Type="boolean" Dim="8">true	true	false	false	false	false	false	false</Param>
    <Param Name="CursorN" Type="double" Dim="8">885	885	0	0	0	0	0	0</Param>
    <Param Name="CursorXDiff" Type="double" Dim="8">221	221	7397.18	0	0	0	0	0</Param>
    <Param Name="CursorYDiff" Type="double" Dim="8">-0.000230468	-0.000403555	-190.351	0	0	0	0	0</Param>
    <Param Name="CursorMean" Type="double" Dim="8">0.000292263	0.000312495	0	0	0	0	0	0</Param>
    <Param Name="CursorRMS" Type="double" Dim="8">0.00130005	0.00160029	0	0	0	0	0	0</Param>
    <Param Name="CursorStdDev" Type="double" Dim="8">0.00126749	0.00157037	0	0	0	0	0	0</Param>
    <Param Name="CursorSum" Type="double" Dim="8">0.258653	0.276558	0	0	0	0	0	0</Param>
    <Param Name="CursorSqrSum" Type="double" Dim="8">0.00149576	0.00226644	0	0	0	0	0	0</Param>
    <Param Name="CursorArea" Type="double" Dim="8">0.0646632	0.0691395	0	0	0	0	0	0</Param>
    <Param Name="CursorRMSArea" Type="double" Dim="8">0.0193375	0.0238035	0	0	0	0	0	0</Param>
    <Param Name="CursorPeakX" Type="double" Dim="8">6.25	17.75	0	0	0	0	0	0</Param>
    <Param Name="CursorPeakY" Type="double" Dim="8">0.0133265	0.0222269	0	0	0	0	0	0</Param>
    <Param Name="ConfigAutoConfig" Type="boolean">true</Param>
    <Param Name="ConfigRespectUser" Type="boolean">true</Param>
    <Param Name="ConfigAutoAxes" Type="boolean">true</Param>
    <Param Name="ConfigAutoBin" Type="boolean">true</Param>
    <Param Name="ConfigAutoTimeAdjust" Type="boolean">true</Param>
    <Param Name="StyleTitle" Type="string">Power spectrum</Param>
    <Param Name="StyleTitleAlign" Type="int">13</Param>
    <Param Name="StyleTitleAngle" Type="double">0</Param>
    <Param Name="StyleTitleColor" Type="int">1</Param>
    <Param Name="StyleTitleFont" Type="int">62</Param>
    <Param Name="StyleTitleSize" Type="double">0.05</Param>
    <Param Name="StyleMargin" Type="double" Dim="4">0.1	0.05	0.1	0.18</Param>
    <Param Name="AxisXTitle" Type="string">Frequency</Param>
    <Param Name="AxisXAxisAttrAxisColor" Type="int">1</Param>
    <Param Name="AxisXAxisAttrLabelColor" Type="int">1</Param>
    <Param Name="AxisXAxisAttrLabelFont" Type="int">62</Param>
    <Param Name="AxisXAxisAttrLabelOffset" Type="double">0.005</Param>
    <Param Name="AxisXAxisAttrLabelSize" Type="double">0.04</Param>
    <Param Name="AxisXAxisAttrNdividions" Type="int">510</Param>
    <Param Name="AxisXAxisAttrTickLength" Type="double">0.03</Param>
    <Param Name="AxisXAxisAttrTitleOffset" Type="double">1.4</Param>
    <Param Name="AxisXAxisAttrTitleSize" Type="double">0.042</Param>
    <Param Name="AxisXAxisAttrTitleColor" Type="int">1</Param>
    <Param Name="AxisXGrid" Type="boolean">true</Param>
    <Param Name="AxisXBothSides" Type="boolean">true</Param>
    <Param Name="AxisXCenterTitle" Type="boolean">true</Param>
    <Param Name="AxisYTitle" Type="string">Magnitude</Param>
    <Param Name="AxisYAxisAttrAxisColor" Type="int">1</Param>
    <Param Name="AxisYAxisAttrLabelColor" Type="int">1</Param>
    <Param Name="AxisYAxisAttrLabelFont" Type="int">62</Param>
    <Param Name="AxisYAxisAttrLabelOffset" Type="double">0.005</Param>
    <Param Name="AxisYAxisAttrLabelSize" Type="double">0.04</Param>
    <Param Name="AxisYAxisAttrNdividions" Type="int">510</Param>
    <Param Name="AxisYAxisAttrTickLength" Type="double">0.03</Param>
    <Param Name="AxisYAxisAttrTitleOffset" Type="double">0.95</Param>
    <Param Name="AxisYAxisAttrTitleSize" Type="double">0.045</Param>
    <Param Name="AxisYAxisAttrTitleColor" Type="int">1</Param>
    <Param Name="AxisYGrid" Type="boolean">true</Param>
    <Param Name="AxisYBothSides" Type="boolean">true</Param>
    <Param Name="AxisYCenterTitle" Type="boolean">true</Param>
    <Param Name="LegendShow" Type="boolean">true</Param>
    <Param Name="LegendPlacement" Type="int">0</Param>
    <Param Name="LegendXAdjust" Type="double">0</Param>
    <Param Name="LegendYAdjust" Type="double">0</Param>
    <Param Name="LegendSymbolStyle" Type="int">0</Param>
    <Param Name="LegendTextStyle" Type="int">1</Param>
    <Param Name="LegendSize" Type="double">1</Param>
    <Param Name="LegendText[0]" Type="string">2x fringe velocity</Param>
    <Param Name="LegendText[1]" Type="string">1x fringe velocity</Param>
    <Param Name="LegendText[2]" Type="string"></Param>
    <Param Name="LegendText[3]" Type="string"></Param>
    <Param Name="LegendText[4]" Type="string"></Param>
    <Param Name="LegendText[5]" Type="string"></Param>
    <Param Name="LegendText[6]" Type="string"></Param>
    <Param Name="LegendText[7]" Type="string"></Param>
    <Param Name="ParamShow" Type="boolean">true</Param>
    <Param Name="ParamT0" Type="boolean">true</Param>
    <Param Name="ParamAvg" Type="boolean">true</Param>
    <Param Name="ParamSpecial" Type="boolean">true</Param>
    <Param Name="ParamTimeFormatUTC" Type="boolean">true</Param>
    <Param Name="ParamTextSize" Type="double">0.04</Param>
  </LIGO_LW>
  <LIGO_LW Name="Plot[1][1]" Type="Plot">
    <Param Name="Flag" Type="string">Settings</Param>
    <Param Name="Name" Type="string">Default</Param>
    <Param Name="TracesGraphType" Type="string">Coherence</Param>
    <Param Name="TracesActive[0]" Type="boolean">true</Param>
    <Param Name="TracesAChannel[0]" Type="string" Unit="channel">L1:LSC-DARM_ERR</Param>
    <Param Name="TracesBChannel[0]" Type="string" Unit="channel">L1:LSC-MICH_CTRL</Param>
    <Param Name="TracesActive[1]" Type="boolean">true</Param>
    <Param Name="TracesAChannel[1]" Type="string" Unit="channel">L1:LSC-DARM_ERR</Param>
    <Param Name="TracesBChannel[1]" Type="string" Unit="channel">L1:LSC-PRC_CTRL</Param>
    <Param Name="TracesActive[2]" Type="boolean">false</Param>
    <Param Name="TracesAChannel[2]" Type="string" Unit="channel"></Param>
    <Param Name="TracesBChannel[2]" Type="string" Unit="channel"></Param>
    <Param Name="TracesActive[3]" Type="boolean">false</Param>
    <Param Name="TracesAChannel[3]" Type="string" Unit="channel"></Param>
    <Param Name="TracesBChannel[3]" Type="string" Unit="channel"></Param>
    <Param Name="TracesActive[4]" Type="boolean">false</Param>
    <Param Name="TracesAChannel[4]" Type="string" Unit="channel"></Param>
    <Param Name="TracesBChannel[4]" Type="string" Unit="channel"></Param>
    <Param Name="TracesActive[5]" Type="boolean">false</Param>
    <Param Name="TracesAChannel[5]" Type="string" Unit="channel"></Param>
    <Param Name="TracesBChannel[5]" Type="string" Unit="channel"></Param>
    <Param Name="TracesActive[6]" Type="boolean">false</Param>
    <Param Name="TracesAChannel[6]" Type="string" Unit="channel"></Param>
    <Param Name="TracesBChannel[6]" Type="string" Unit="channel"></Param>
    <Param Name="TracesActive[7]" Type="boolean">false</Param>
    <Param Name="TracesAChannel[7]" Type="string" Unit="channel"></Param>
    <Param Name="TracesBChannel[7]" Type="string" Unit="channel"></Param>
    <Param Name="TracesPlotStyle" Type="int" Dim="8">0	0	0	0	0	0	0	0</Param>
    <Param Name="TracesLineAttrColor" Type="int" Dim="8">2	4	3	28	6	7	5	1</Param>
    <Param Name="TracesLineAttrStyle" Type="int" Dim="8">1	1	1	1	1	1	1	1</Param>
    <Param Name="TracesLineAttrWidth" Type="double" Dim="8">1	1	1	1	1	1	1	1</Param>
    <Param Name="TracesMarkerAttrColor" Type="int" Dim="8">2	4	3	28	6	7	5	1</Param>
    <Param Name="TracesMarkerAttrStyle" Type="int" Dim="8">20	22	21	23	29	27	2	5</Param>
    <Param Name="TracesMarkerAttrSize" Type="double" Dim="8">1	1	1	1	1	1	1	1</Param>
    <Param Name="TracesBarAttrColor" Type="int" Dim="8">2	4	3	28	6	7	5	1</Param>
    <Param Name="TracesBarAttrStyle" Type="int" Dim="8">1001	1001	1001	1001	1001	1001	1001	1001</Param>
    <Param Name="TracesBarAttrWidth" Type="double" Dim="8">0.1	0.1	0.1	0.1	0.1	0.1	0.1	0.1</Param>
    <Param Name="RangeAxisScale" Type="int" Dim="2">1	0</Param>
    <Param Name="RangeRange" Type="int" Dim="2">0	1</Param>
    <Param Name="RangeRangeFrom" Type="double" Dim="2">0	0</Param>
    <Param Name="RangeRangeTo" Type="double" Dim="2">8139.57	1</Param>
    <Param Name="RangeBin" Type="int">1</Param>
    <Param Name="RangeBinLogSpacing" Type="boolean">true</Param>
    <Param Name="UnitsXValues" Type="int">0</Param>
    <Param Name="UnitsYValues" Type="int">0</Param>
    <Param Name="UnitsXUnit" Type="string">default</Param>
    <Param Name="UnitsYUnit" Type="string">default</Param>
    <Param Name="UnitsXMag" Type="int">0</Param>
    <Param Name="UnitsYMag" Type="int">0</Param>
    <Param Name="UnitsXSlope" Type="double">1</Param>
    <Param Name="UnitsYSlope" Type="double">1</Param>
    <Param Name="UnitsXOffset" Type="double">0</Param>
    <Param Name="UnitsYOffset" Type="double">0</Param>
    <Param Name="CursorActive" Type="boolean" Dim="2">false	false</Param>
    <Param Name="CursorTrace" Type="int">0</Param>
    <Param Name="CursorStyle" Type="int">1</Param>
    <Param Name="CursorType" Type="int">0</Param>
    <Param Name="CursorX" Type="double" Dim="2">0.250087	1000.46</Param>
    <Param Name="CursorH" Type="double" Dim="2">0	100</Param>
    <Param Name="CursorValid" Type="boolean" Dim="8">true	true	false	false	false	false	false	false</Param>
    <Param Name="CursorN" Type="double" Dim="8">14800	14800	0	0	0	0	0	0</Param>
    <Param Name="CursorXDiff" Type="double" Dim="8">7397.18	7397.18	0	0	0	0	0	0</Param>
    <Param Name="CursorYDiff" Type="double" Dim="8">-0.0285121	-0.134547	0	0	0	0	0	0</Param>
    <Param Name="CursorMean" Type="double" Dim="8">0.187171	0.183751	0	0	0	0	0	0</Param>
    <Param Name="CursorRMS" Type="double" Dim="8">0.248896	0.246286	0	0	0	0	0	0</Param>
    <Param Name="CursorStdDev" Type="double" Dim="8">0.164068	0.163994	0	0	0	0	0	0</Param>
    <Param Name="CursorSum" Type="double" Dim="8">2770.12	2719.51	0	0	0	0	0	0</Param>
    <Param Name="CursorSqrSum" Type="double" Dim="8">916.852	897.718	0	0	0	0	0	0</Param>
    <Param Name="CursorArea" Type="double" Dim="8">811.387	822.357	0	0	0	0	0	0</Param>
    <Param Name="CursorRMSArea" Type="double" Dim="8">10.6901	11.1993	0	0	0	0	0	0</Param>
    <Param Name="CursorPeakX" Type="double" Dim="8">59.9995	239.861	0	0	0	0	0	0</Param>
    <Param Name="CursorPeakY" Type="double" Dim="8">0.937457	0.963756	0	0	0	0	0	0</Param>
    <Param Name="ConfigAutoConfig" Type="boolean">true</Param>
    <Param Name="ConfigRespectUser" Type="boolean">true</Param>
    <Param Name="ConfigAutoAxes" Type="boolean">true</Param>
    <Param Name="ConfigAutoBin" Type="boolean">true</Param>
    <Param Name="ConfigAutoTimeAdjust" Type="boolean">true</Param>
    <Param Name="StyleTitle" Type="string">Coherence</Param>
    <Param Name="StyleTitleAlign" Type="int">13</Param>
    <Param Name="StyleTitleAngle" Type="double">0</Param>
    <Param Name="StyleTitleColor" Type="int">1</Param>
    <Param Name="StyleTitleFont" Type="int">62</Param>
    <Param Name="StyleTitleSize" Type="double">0.05</Param>
    <Param Name="StyleMargin" Type="double" Dim="4">0.1	0.05	0.1	0.18</Param>
    <Param Name="AxisXTitle" Type="string">Frequency</Param>
    <Param Name="AxisXAxisAttrAxisColor" Type="int">1</Param>
    <Param Name="AxisXAxisAttrLabelColor" Type="int">1</Param>
    <Param Name="AxisXAxisAttrLabelFont" Type="int">62</Param>
    <Param Name="AxisXAxisAttrLabelOffset" Type="double">0.005</Param>
    <Param Name="AxisXAxisAttrLabelSize" Type="double">0.04</Param>
    <Param Name="AxisXAxisAttrNdividions" Type="int">510</Param>
    <Param Name="AxisXAxisAttrTickLength" Type="double">0.03</Param>
    <Param Name="AxisXAxisAttrTitleOffset" Type="double">1.4</Param>
    <Param Name="AxisXAxisAttrTitleSize" Type="double">0.042</Param>
    <Param Name="AxisXAxisAttrTitleColor" Type="int">1</Param>
    <Param Name="AxisXGrid" Type="boolean">true</Param>
    <Param Name="AxisXBothSides" Type="boolean">true</Param>
    <Param Name="AxisXCenterTitle" Type="boolean">true</Param>
    <Param Name="AxisYTitle" Type="string">Coherence</Param>
    <Param Name="AxisYAxisAttrAxisColor" Type="int">1</Param>
    <Param Name="AxisYAxisAttrLabelColor" Type="int">1</Param>
    <Param Name="AxisYAxisAttrLabelFont" Type="int">62</Param>
    <Param Name="AxisYAxisAttrLabelOffset" Type="double">0.005</Param>
    <Param Name="AxisYAxisAttrLabelSize" Type="double">0.04</Param>
    <Param Name="AxisYAxisAttrNdividions" Type="int">510</Param>
    <Param Name="AxisYAxisAttrTickLength" Type="double">0.03</Param>
    <Param Name="AxisYAxisAttrTitleOffset" Type="double">0.95</Param>
    <Param Name="AxisYAxisAttrTitleSize" Type="double">0.045</Param>
    <Param Name="AxisYAxisAttrTitleColor" Type="int">1</Param>
    <Param Name="AxisYGrid" Type="boolean">true</Param>
    <Param Name="AxisYBothSides" Type="boolean">true</Param>
    <Param Name="AxisYCenterTitle" Type="boolean">true</Param>
    <Param Name="LegendShow" Type="boolean">true</Param>
    <Param Name="LegendPlacement" Type="int">0</Param>
    <Param Name="LegendXAdjust" Type="double">0</Param>
    <Param Name="LegendYAdjust" Type="double">0</Param>
    <Param Name="LegendSymbolStyle" Type="int">0</Param>
    <Param Name="LegendTextStyle" Type="int">0</Param>
    <Param Name="LegendSize" Type="double">1</Param>
    <Param Name="LegendText[0]" Type="string"></Param>
    <Param Name="LegendText[1]" Type="string"></Param>
    <Param Name="LegendText[2]" Type="string"></Param>
    <Param Name="LegendText[3]" Type="string"></Param>
    <Param Name="LegendText[4]" Type="string"></Param>
    <Param Name="LegendText[5]" Type="string"></Param>
    <Param Name="LegendText[6]" Type="string"></Param>
    <Param Name="LegendText[7]" Type="string"></Param>
    <Param Name="ParamShow" Type="boolean">true</Param>
    <Param Name="ParamT0" Type="boolean">true</Param>
    <Param Name="ParamAvg" Type="boolean">true</Param>
    <Param Name="ParamSpecial" Type="boolean">true</Param>
    <Param Name="ParamTimeFormatUTC" Type="boolean">true</Param>
    <Param Name="ParamTextSize" Type="double">0.04</Param>
  </LIGO_LW>
  <LIGO_LW Name="Index" Type="Index">
    <Param Name="Flag" Type="string">Result</Param>
    <Param Name="Entry[0]" Type="string">MasterIndex:
      Entry[0] = MasterIndex;
      Entry[1] = PowerSpectrum[0];
      Entry[2] = CrossCorrelation[0];
      Entry[3] = Coherence[0];</Param>
    <Param Name="Entry[1]" Type="string">PowerSpectrum[0]:
      Channel[0] = L1:LSC-DARM_ERR;
      Name[0] = Result[0];
      Offset[0] = 0;
      Length[0] = 29601;
      Channel[1] = L1:LSC-MICH_CTRL;
      Name[1] = Result[1];
      Offset[1] = 0;
      Length[1] = 29601;
      Channel[2] = L1:LSC-PRC_CTRL;
      Name[2] = Result[2];
      Offset[2] = 0;
      Length[2] = 29601;</Param>
    <Param Name="Entry[2]" Type="string">CrossCorrelation[0]:
      ChannelA[0] = L1:LSC-DARM_ERR;
      ChannelB[0] = L1:LSC-DARM_ERR;
      ChannelB[1] = L1:LSC-MICH_CTRL;
      ChannelB[2] = L1:LSC-PRC_CTRL;
      Name[0][1] = Result[3];
      Offset[0][1] = 0;
      Length[0][1] = 29601;
      Name[0][2] = Result[3];
      Offset[0][2] = 29601;
      Length[0][2] = 29601;</Param>
    <Param Name="Entry[3]" Type="string">Coherence[0]:
      ChannelA[0] = L1:LSC-DARM_ERR;
      ChannelB[0] = L1:LSC-DARM_ERR;
      ChannelB[1] = L1:LSC-MICH_CTRL;
      ChannelB[2] = L1:LSC-PRC_CTRL;
      Name[0][1] = Result[4];
      Offset[0][1] = 0;
      Length[0][1] = 29601;
      Name[0][2] = Result[4];
      Offset[0][2] = 29601;
      Length[0][2] = 29601;</Param>
  </LIGO_LW>
  <LIGO_LW Name="Reference[1]" Type="Spectrum">
    <Param Name="Flag" Type="string">Result</Param>
    <Param Name="Subtype" Type="int">1</Param>
    <Param Name="f0" Type="double" Unit="Hz">0</Param>
    <Param Name="df" Type="double" Unit="Hz">0.25</Param>
    <Time Name="t0" Type="GPS">916817704.0</Time>
    <Param Name="dt" Type="double" Unit="s">0.25</Param>
    <Param Name="BW" Type="double" Unit="Hz">0.374994</Param>
    <Param Name="Window" Type="int">1</Param>
    <Param Name="AverageType" Type="int">0</Param>
    <Param Name="Averages" Type="int">1</Param>
    <Param Name="N" Type="int">29601</Param>
    <Param Name="M" Type="int">1</Param>
    <Param Name="ChannelA" Type="string" Unit="channel">L1:LSC-DARM_ERR</Param>
    <Array Type="float">
      <Dim>29601</Dim>
      <Stream Encoding="BigEndian,base64">
OdOxWzoI8vg54OeJOicSsTpb0Y86FnwnOgKZxzpZNPg6mkHvOqME+zoqJ4o6Kwts
OgKzXTnJQho58gsBOgSJ3To3tHU6WQMWOlOiXjqRqWY6wwSMOu/+qDuPAII77HMU
PC7ZhDyPsns8QlxhO8P39jucaTc72qXXO/vk1zuL4Z47XxigO44kTzvD7TY7x+i/
O5Fk0Ttl+m87SBikO39TlTujtbs7m1jjO4MHqzuHxOk7b+5AO0DeaTsOeWI7zC1Q
O91jWTsvr5o6uhs+OshbzDrGQQc6Y+CkOgiuvDqJUDs6z9RIOtA32DrS8Ug7BgVJ
OwA/MjsFi8066jE1Oyzz4zsHTaA6hE54OqPzdzqT2806mczqPA7HUzylWck8thUl
O+FL+jqOqj46iG4mOk1wQTpFObU6NpiQOZLN4zjfa1U47QcuOLpUsDhB2284RQvL
OGGd0TgTZm44Ap4MOBTTuTgQeJs4HXexN/dyRzfa0fc4FaKYOB+EzTgXQ8M4KdZP
N/IWZDfH7rs38CXROEqC0DiP1tI4rquCONWP2TiZXp44D1CsOAI3JjgQf5Q4H+jp
OAEefzgQPMc4M7CIOC9ZLTgJv784CRABOA6MkjfoKVA328rdN9yfZjgiDok4PBTN
OB9pwTfVETQ3xmEjN77PsTgJcbQ4GJL1N+uToTfXIJY35z3GOBGfhDgODZA4Fjt3
OBswcjhMHP84XDJIOB0OXzgVkOM4ESYWODpkejih7KE4+MRJOPoY3jiQCNQ4bkOu
OG04djhsReY4cTR6OE/jTDhbEd84dEiqOFlSTThHTME4L0LjOEYkHzhwFDM4O6ha
OD6MoDhfiDc4W/oKOFJlyDg09wY4PqTGODMIjjhaiC04f1mkOGIQYjg5tFU4h38+
OIoNpDhnuFs4iqHBOGrBQzh+XQk4hyU7OJXh0ziDT+A4b0tOOGOBIDiJoLw4tGnE
OITMSjhmW5M4eYu/ODlv+jhHUG04XpHuOHm61jhd6PI4WqLIOICpVzhlGhw4eFaV
OEZ6Gzh9aMc4OdUQOGzRiTiOINA4eL6wOHm6wzhvTmw4foNyOHo7pziOsJ44iyAB
OJJQ2DiSvZU4QYN1OIVYDzhVt+Q4cOcJOFAgRDiLPzY4ghjMOFw/3ziVzcQ4dtTQ
OIotojiHGw44hYX6OHOJJThxe/k4dufMOFbzLziCF/44gDPxOIe51jiexqE4g1q7
OKwBsziT3Lo4mD6kOKPudziGYWA4lMxcOIIUADh9xTw4dhKxOEqoIThraRk4b0cc
OQUqiDiDJ+k4EqjuOB4VxDgFn1A4B8I7OBsqADgCZEE4FI5DOBPQ4zgUrT44Fb57
OB4gwTgP1BA4E/x2OAs/qTf/T1U4AMhUN+S0kjfdyJA30kGXN725bze5Qsc3q2v/
N6N+pjee71c3mqP9N5Cu8zeMUgg3h6bYN3kz8TeEMIg3cOmxN3CcIDdybg43Vajs
N1uAETdLyJI3QF69N0NlKzctaok3LQ1zNx5onDcUCok3DxVdNv44fDbyjoU22saw
NsurzTa4inE2oFWdNpUGBTZ+2L02bQ3uNmhk7TZTjFM2W9OTNlhSNDZIAdw2XoCt
NlFyTzZWIOk2V5g8NkNfmDZA/i02K0C2NiBVZTYa+3E2AlTwNfjnCDXmV9Q1yDud
Nbq6eDWgBms1lea3NZNkxDWI3vQ1iIGQNZifhjWWdL81k0QJNY8fDjWIvqQ1ieyk
NYol5TV8brA1cwNCNWdKjTVjlRw1T9mPNUD8fjUlIuc1EN9DNRQEIjT4erY00P3v
NPsVtDULwHk04oO2NOJ5tzTecUc0yon+NNq65zTUSsE0uorsNMBMIjS5eU80u8FV
NL3wGjSsyD40lgt4NKKu5DSRdgA0kWvTNK9luDSRBpM0jMWjNJLBhzSFzvw0TRk/
NFMhhzRjhfw0WXdwNHmacTSV6Bc0by8RNE1w3TRCx/Y0ZSrkNChxQDQnvFk0baSO
NDhXzTQcgfc0PAVXNHgnojR+j7w0S1GjNB6lTjQgWYY0JijqNH7ZCzSF9EA0YyNy
NEcPNDQ3WMY0QlIQNBL1AzQm4eU0Cjm7NBYgcjQOpu80BDUFNCw74jQs6dE0NeD2
NE3n2DQ2Dug0NacvNC3p/jQXnSo0HDxNNC14xTQlICg0OpbGNBJOBjQqx0s0P2co
NEFCljQqM800GHQxNA3mFzQzJTw0Lz8wNCkQ/TQbPAQz8Ji/NB7iujRwV400Q1to
NBDQfzP+YzA0KaI5NBE7rDQk5QQ0TvydNCx3KjQjdKgz/24UNBAxJzQoYmo0EwQt